export const RESTART_WALLET_CONNECT     = 'RESTART_WALLET_CONNECT';
export const WALLET_DISCONNECT_START    = 'WALLET_DISCONNECT_START';
export const WALLET_DISCONNECT_SUCCESS  = 'WALLET_DISCONNECT_SUCCESS';
export const WALLET_CONNECT_SUCCESS     = 'WALLET_CONNECT_SUCCESS';